subscriptions:
  - name: grafana-operator
    channel: v4
    installPlanApproval: Automatic
    source: community-operators
    sourceNamespace: openshift-marketplace
    startingCSV: grafana-operator.v4.1.1

operatorGroups:
  - name: aro-thanos-af
    targetNamespace: ~
