apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-azure
  namespace: openshift-logging
stringData:
  account_name: "{{ .Values.aro.storageAccount }}"
  account_key: "{{ .Values.aro.storageAccountKey }}"
  container: "{{ .Values.aro.storageContainer }}"
  environment: "AzureGlobal"
